### ISSUE TITLE
On Nivelles platform, when sending a newsletter, logo is displayed in the preview but not in the actual mail that the user receives

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#100]
https://nivelles.monopinion.belgium.be/admin/newsletters/3
Preview of the newsletter is ok: 
![capture d ecran 2018-05-23 a 12 26 09](https://user-images.githubusercontent.com/29771726/40419113-98b56516-5e84-11e8-9686-3e5d20ac52c4.png)

What they received through Gandi is not ok:
![capture d ecran 2018-05-23 a 12 28 42](https://user-images.githubusercontent.com/29771726/40419392-7d4f365c-5e85-11e8-99e3-59fea2e64dbe.png)

What I received on Gmail is not ok either: 
![capture d ecran 2018-05-23 a 12 32 37](https://user-images.githubusercontent.com/29771726/40419777-b4c581c6-5e86-11e8-8fb2-c4a1bf4029a9.png)

But the newsletter is correctly displayed when you click on "Voir la version web":
https://nivelles.monopinion.belgium.be/newsletters/4
![capture d ecran 2018-05-23 a 12 44 03](https://user-images.githubusercontent.com/29771726/40419916-ff4b81fa-5e86-11e8-918c-5e2fbb8d1443.png)

I did a test with http://decidim-loiret.herokuapp.com/admin/newsletters/2 and it works fine:
![capture d ecran 2018-05-23 a 12 46 24](https://user-images.githubusercontent.com/29771726/40420039-58f19abe-5e87-11e8-916d-ff27f97f78d1.png)

I don't know if the problem is the email client, the configuration on the server side or the size/type of their logo (which seems pretty standard though)

**Comment by moustachu** [comment]
it comes from the image URL which is _relative_ (`/...`) instead of _absolute_ (`https://...`) 

We should see if it could be fix in the actual app (osp-app@alt/bosa) `app/views/decidim/layouts/mailer.rb`

**Comment by moustachu** [comment]
Not sure about the fix here ... 

✅ It worked on Heroku deployments because images stored via S3 (Amazon) are stored in DB with their full URL (or maybe carierwave is also doing some magic but it work).

🔴 it failed on self hosted decidim because image URLs are stored in DB with their relative path and put like that in the mail templates 😭 

I did a quick fix by setting `Rails.application.config.action_mailer.asset_host` but it can only work for one domain (which will always give access to an image on the server). 

In a multi tenant (organization) use of the platform (eg. bosa :wink:) it can be confusing since the images will have URLs which do not correspond exactly to the organization domain (so good to remember in case of firewall / spam issues). 

see the patch in https://github.com/OpenSourcePolitics/osp-app/commit/78a57a72cdb2a9121fa9e79844aef2d5ba881848

**Comment by moustachu** [comment]
My point is that it work _logically_ as is but it could be improved for multi tenant. Maybe to be postponed to en EPIC multi tenant sprint (with the social login management 😉)
