### ISSUE TITLE
Refactoring module votes_weight

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#116]
- In 0.12, when activated, the module is not displayed on the proposals index but it is displayed on the show of a proposal. It might have to do with major changes in 0.12, like the replacement of `Abilities` by `Permissions`. 

- It is possible to activate both modules (Votes simple / Votes for/neutral/against) at the same time when it should not be possible
![capture d ecran 2018-06-20 a 16 05 52](https://user-images.githubusercontent.com/29771726/41663504-df84df50-74a3-11e8-9dcb-708a7cf4736e.png)

- Rethinking of the design is needed : On the show, display of the buttons is not good (no margin) ; on the index the actual design might not fit with the new design of the proposal cards
![capture d ecran 2018-06-20 a 15 57 29](https://user-images.githubusercontent.com/29771726/41663380-9aa9f8e8-74a3-11e8-9877-026b00ae9545.png)

- When ordering proposals by "The most liked", the proposal with the most votes in total is first. 
E.g proposal "A" has 2 votes for, 1 neutral, 15 against and proposal "B" has 12 votes for, 2 neutral and 0 against. Proposal "A" will be first. It should be proposal "B" (== the one that has the most votes "for")

- In the votes statistics, all the votes (for/neutral/against) are counted. Should it be only the votes "for" ?

**Comment by moustachu** [comment]
@juliesimon 

With the last(s) commit(s) : 

1. Abilities --> Permissions ✅ 
2. Weighted votes on proposals index ✅
3. UX design ✅
4. Module activation ✅(thanks @juliesimon : https://github.com/OpenSourcePolitics/decidim/commit/92ef018713b0206217d8d984d9d70c6c0c5370ef )
5. Ordering & Filtering 🔴 : not yet ... 
--> I might add that there're warnings in the Console because of duplicate ID in the filter form
6. Votes statistics 🔴: good question ... the data is correct because it counts all the votes.  
Because of the weight, we could consider displaying the score (sum of the vote's weight) and the participation (total votes count). But the breakdown of votes is displayed on the button.
