### ISSUE TITLE
What changes between in the test architecture between 0.12 and 0.14.0.dev (master) ?

### ISSUE THREAD

**Issue by moustachu** [OpenSourcePolitics/decidim#134]
It's not about the coverage but the way the test suite are executed ...

- `build_design_app` has disapeared
- `main` seems to be blocking the rest of the suite 

My point is to understand the purpose of these changes : 
- `main` tests fails because of i18n sanity (and missing keys) and we might have these for a long time regarding our customization workflow
- Regarding the last point, the former test suite architecture was more suitable for us
- What the benefits of the new architecture ?

--> Don't hesitate to ping others on Gitter ;) 

### `0.12-test`
![image](https://user-images.githubusercontent.com/464350/42751596-938b0c3a-88eb-11e8-9835-bb6f10580a8c.png)

### `decidim-master-with-test-navbar-links`
![image](https://user-images.githubusercontent.com/464350/42751636-afbb32e0-88eb-11e8-9cdc-40d783376d7e.png)

**Comment by armandfardeau** [comment]
Thanks to Marc Riera, we have an answer: 
This reordering has been done to shorten failing builds. Before this change, the suite might fail due to lint errors/i18n sanity, but keep running all other tests. This blocks our resources, since we already know you’ll have to push again to fix those lint errors (otherwise we won’t merge the PR)
so we first check those lint errors, i18n sanity, etc
and then we run the proper tests

**Comment by moustachu** [comment]
Okay so we DO NEED to fix all those i18n sanity checks 😭
