### ISSUE TITLE
Searchbar not working on https://atelierdevosidees.loiret.fr

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#153]
For instance, i try to look for "parc" but it does not show any result whereas it should.

https://atelierdevosidees.loiret.fr/search?utf8=%E2%9C%93&term=parc

**Comment by moustachu** [comment]
@juliesimon This one should be interesting for future issues.

At first I thought that Meetings were not showing because they were past but it seems it's not the correct behavior on the main search page (past meetings should be visible / searchable). 

The problem (don't know the cause but let's put that on code update & migrations) was in fact that the search index were not up to date. 

--> We are talking about all the things around `Decidim::Searchable` & `Decidim::SearchableResource`

## The fix 

--> was not straight forward and commands might need to be executed multiple time (or maybe it's because the DB is working in background)

In the Rails console (`bundle exec rails c`)

```ruby 
# From decidim-core/db/migrate/20180206143340_fix_reference_for_all_resources.rb
models = ActiveRecord::Base.descendants.select { |c| c.included_modules.include?(Decidim::HasReference) }

models.each do |model|
  model.find_each(&:touch)
end

# From decidim-core/lib/decidim/searchable.rb
Decidim::Proposals::Proposal.all.each do |p|
  p.try_add_to_index_as_search_resource
  p.try_update_index_for_search_resource
end
```
