### ISSUE TITLE
Survey already answered when it shouldn't

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#328]
**Describe the bug**
To be complete, when the survey is published even though there are no questions, as a user who answered the original survey, I am told i have already answered the survey. When questions are added, I see the survey as expected.
To link with => #327

**To Reproduce**
As a user who answered the original survey
1. Go to 'https://steamroll.osp.cat/processes/test-copie-composant/f/76/'
2. See error
<img width="1270" alt="screen shot 2018-10-30 at 10 19 27" src="https://user-images.githubusercontent.com/32680605/47708628-c403f480-dc2e-11e8-85a9-1040714a2f48.png">

**Expected behavior**
As a user, when I go to the published and copied survey, I shouldn't see a message telling me I have already answered the survey. I should see no message.

**Comment by armandfardeau** [comment]
@lu-hamani 
Currently, when a user copies a PP with a survey component inside, the survey component is not published directly. 

![image](https://user-images.githubusercontent.com/20232956/49076808-29e99900-f23a-11e8-8f9d-c3e02c1bfdf0.png)

Therefore, when you publish it, the survey displays a correct error message : 

![image](https://user-images.githubusercontent.com/20232956/49076856-3f5ec300-f23a-11e8-8f8e-2aad32ce3133.png)

Since there is no error anymore, I'm closing this issue, feel free to re-open it if I made any mistakes.
