### ISSUE TITLE
Projects list design improvement

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#340]
**Is your feature request related to a problem? Please describe.**
When I want to vote for a project, the list I am given is not practical since there are a lot of projects and I can only browse through very few of them. I can't remember all the projects I already look to make my choice and I can't search for the type of project I want to vote for easily.

**Describe the solution you'd like**
Solution n°1 : Projects are be displayed as cards so that more can be directly shown to the user. 
Solution n°2 : Projects are still displayed as a list, yet their presentation is enhanced.
Common characteristic : Container showing the choices already made by the user should be fixed so that he can see the projects he has already chose even as he scrolls down to see more projects.

**Mockups**
Coming soon

**Comment by moustachu** [comment]
**Level 3** because we miss the mockups and it's huge tasks on its own. 

This could be simplified if we try to use what have been done on Proposals for "Nouvelle Aquitaine". 

<img width="1240" alt="capture d ecran 2019-02-06 a 10 57 31" src="https://user-images.githubusercontent.com/464350/52333724-48b89880-29fe-11e9-95ea-93c46b0e1e32.png">

<img width="1215" alt="capture d ecran 2019-02-06 a 10 57 04" src="https://user-images.githubusercontent.com/464350/52333740-4ce4b600-29fe-11e9-94ba-9f3eec401246.png">

@lu-hamani If you don't have time to pull out the mockups, just list the informations (and their display format) you want to display.

**Comment by lu-hamani** [comment]
> **Level 3** because we miss the mockups and it's huge tasks on its own.
> @lu-hamani If you don't have time to pull out the mockups, just list the informations (and their display format) you want to display.

Mockups are being created as we speak. Until they are done and discussed, there we'll be no launch on this one.

**Comment by lu-hamani** [comment]
@moustachu , @armandfardeau 

Here are first drafts for the mockups using pre-existing elements within Decidim for project listing.

No votes displayed**
![project list without vote](https://user-images.githubusercontent.com/32680605/52557539-09b88780-2df0-11e9-90b1-eab861c6d9ed.png)

**Votes displayed**
![project list](https://user-images.githubusercontent.com/32680605/52557538-09b88780-2df0-11e9-8318-e204139d84f8.png)
