### ISSUE TITLE
Filter proposals in back office

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#456]
**User Story**
As admin, I want to filter the proposals by category and by state so that I see only the proposals I want to see.
 
**Acceptance Criteria**
When I click on the filter caret, I am proposed to select which filter I want to apply to the list of proposals. When I click on the filter I want, only the proposals pertaining to the filter I chose are displayed.

**Mockups**
View filters
![proposals search filters](https://user-images.githubusercontent.com/32680605/52118970-06671400-2618-11e9-92ff-fd59b16d3244.png)

Selecting a filter
![proposals search filters choices](https://user-images.githubusercontent.com/32680605/52118979-09fa9b00-2618-11e9-91d0-4ec81b6f493b.png)

**Comment by moustachu** [comment]
This one will be done with #454.  
**Level 3** : 
- because this will need some _clever_ unit tests to check search possibilities
- **but** most of the code is already available through Decidim and ransack 

New UX after code insight : 

<img width="1174" alt="capture d ecran 2019-02-06 a 10 05 14" src="https://user-images.githubusercontent.com/464350/52330838-beb90180-29f6-11e9-99bd-6035bae21129.png">
