### ISSUE TITLE
Server error when trying to access notifications

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#525]
On the Club organization, when I try to access notifications by clicking on the bell icon, I get a server error.

**Comment by moustachu** [comment]
This one is touchy because it concerns author cells in various situation (mostly available on a notifications list ...). 

The exact error is : 
```
ActionView::Template::Error: No route matches {:action=>"show", :controller=>"decidim/profiles", :nickname=>""}, possible unmatched constraints: [:nickname]
```

BCN has begun a fix on this (https://github.com/decidim/decidim/pull/4974), but I fear we might found other cases with all the 0.16 migration : 
- Official contributions
- Managed Users
- Nickname not set (faulty data migrations)
