### ISSUE TITLE
Display of logo and links in footer is not always fine

### ISSUE THREAD

**Issue by juliesimon** [OpenSourcePolitics/decidim#53]
On https://participons.debatpublic.fr/ : logo is on the left (ok) but links are not centered (not ok)
<img width="1391" alt="capture d ecran 2018-03-12 a 16 12 59" src="https://user-images.githubusercontent.com/29771726/37292559-611c55de-2611-11e8-97c3-970187e2feac.png">

On https://cerise.osp.cat/ : logo is in the middle kind of (not ok) but links are centered (ok)
<img width="1391" alt="capture d ecran 2018-03-12 a 16 14 05" src="https://user-images.githubusercontent.com/29771726/37292550-5b896eb8-2611-11e8-9b58-0a982c3f71e7.png">

On https://ecrivons.angers.fr/ : logo on the left (ok) and links centered (ok)
<img width="1391" alt="capture d ecran 2018-03-12 a 16 15 18" src="https://user-images.githubusercontent.com/29771726/37292543-55f1a24a-2611-11e8-85e7-eb5514ccf170.png">

**Comment by moustachu** [comment]
For `alt/CD44` --> fixed in 

https://github.com/OpenSourcePolitics/osp-app/commit/ccd1c34a63bf0039c685af2eb2769d53dbd8308d

https://github.com/OpenSourcePolitics/osp-app/commit/55b0ff12b079578034f2a9b78b8043315b94c4ad

https://github.com/OpenSourcePolitics/osp-app/commit/ba68f7772b5ff87989d2359d136c750e5dd0a025

> yeah ... I was sloppy for this one ...
