### ISSUE TITLE
Links within footer still appear

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim#618]
**Describe the bug**
Pages have been created and the checkbox not to show them in the footer has been ticked. Still they appear in the footer.

**To Reproduce**
1. Go to 'https://kery.osp.cat/'
2. Go to 'https://kery.osp.cat/admin/static_pages/pourquoi_participer/edit'
3. See error

**Expected behavior**
Checking the box should hide the links in the footer

**Screenshots**
<img width="544" alt="Screenshot 2019-04-26 at 14 13 30" src="https://user-images.githubusercontent.com/32680605/56807010-e10c2f80-682d-11e9-8c95-22670bdf31d3.png">
<img width="1054" alt="Screenshot 2019-04-26 at 14 16 12" src="https://user-images.githubusercontent.com/32680605/56807011-e1a4c600-682d-11e9-96b0-5f31c42553c0.png">

**Comment by antoinegaboriau1** [comment]
This bug is solved (thanks) but a page ("télécharger les fichiers de données ouverts") appeared in the footer after the resolution.
It would be appreciable for this page to be deactivated for the administration panel like other pages. 
![image](https://user-images.githubusercontent.com/35924332/57127151-c424ae80-6d8f-11e9-808a-38b92c638e38.png)

**Comment by antoinegaboriau1** [comment]
After talking to the client, they would like to make the link ("télécharger les fichiers de données ouverts") disappear.
