### ISSUE TITLE
VDM - Internet Explorer changing front rendering

### ISSUE THREAD

**Issue by antoinegaboriau1** [OpenSourcePolitics/decidim#646]
On the Val-de-Marne organization, there are problems with the rendering of colors on Internet Explorer.
- Topbar is grey instead of white ;
- In the Meetings functionality, maps are not visible ;
- Colors of all images are generally altered compared to Firefox or Chrome. 

Is there something that can be done to improve these points?

**Comment by armandfardeau** [comment]
@antoinegaboriau1 Download Firefox: https://www.mozilla.org/fr/firefox/new/

Just kidding, I will have a look.

**Comment by armandfardeau** [comment]
* Topbar is grey instead of white -> use #ffffff instead of #ffff FIXED 
![image](https://user-images.githubusercontent.com/20232956/58110229-71505100-7bef-11e9-9ee9-477ca6f5b9f6.png)

* In the Meetings functionality, maps are not visible -> Map is visible (not reproducible) 
![image](https://user-images.githubusercontent.com/20232956/58109763-7fea3880-7bee-11e9-9395-189e7b36da57.png)
* Colors of all images are generally altered compared to Firefox or Chrome -> As far as I know, the pictures are the same on IE than on other browsers. 
![image](https://user-images.githubusercontent.com/20232956/58109948-da839480-7bee-11e9-81b5-bc352149347d.png)
