### ISSUE TITLE
[Accountability] Error in calculating the percentage

### ISSUE THREAD

**Issue by leokante** [OpenSourcePolitics/decidim#750]
**Describe the bug**
There is an error in calculating the percentage. An achievement that doesn't have a percentage sould not modify the global percentage. 

**To Reproduce**
1. Go to https://demo.decidim.opensourcepolitics.eu/processes/modules-decidim/f/6/results?filter%5Bcategory_id%5D=8&filter%5Bscope_id%5D=
2. See error

**Expected behavior**
I expect that the total of "40% of achievements" for one achievement + "no percentage" for another achivement would be equal to 40%
Is that possible ?

**Screenshots**
![image](https://user-images.githubusercontent.com/43004803/61207585-bf686900-a6f5-11e9-998c-48853b64ec66.png)

**Extra data (please complete the following information):**
 - Device: [Desktop]
 - Device OS: [ Windows 10]
 - Browser: [Firefox]
 - Decidim Version: [0.16]
 - Decidim installation: [Demo]

**Additional context**
Should we consider this as an issue ? 
Or should i consider that any achievement listed should impact the global percentage ?
(I have a use case with the city of Rillieux-la-Pape where it would be helpful to be able to incorporate to the list of achievements some achievements that have no impact on the global percentage)

**Comment by virgile-dev** [comment]
@leokante default value when percentage is not filled is 0. 
I guess it's a feature your are asking for here since we would have to create a exception for it to make it work the way you wish, but the priority level is quite low so I'd suggest you propose it on meta decidim. On another note : we should explain the behaviour of the module to our clients so that they understand how it's calculated and fill in the field.
