### ISSUE TITLE
Ghost categories cannot be deleted 

### ISSUE THREAD

**Issue by valentinchaput** [OpenSourcePolitics/decidim#809]
A client decided to rename all the categories of its process. Problem: it created new categories and want to delete the old ones. Old categories are not use neither on Proposals nor on Projects, but we can delete them as an admin + they still appear in the front. 
https://ecrivons.angers.fr/processes/BP2019/f/139/projects?utf8=%E2%9C%93&filter%5Bsearch_text%5D=&filter%5Bcategory_id%5D=72&filter%5Brandom_seed%5D=

How do you explain these "ghost" categories cannot be removed? Do we need to erase them in the db?

We did the same operation last year and didn't face the same issue...

**Comment by moustachu** [comment]
**_⚠️Please use the correct issue template when filling bugs, especially strange ones ⚠️_**

@valentinchaput which are the ones to be deleted ? We need this info to test and see possible error messages or to check the database for corrupt data

**Comment by valentinchaput** [comment]
My bad. 

The old ones to be deleted:
- Confort, convivialité, embellissement
- Culture et patrimoine
- Sports et loisirs
- Mobilité, déplacements
- Propreté, lutte contre les pollutions
- Ville intelligente

The new ones to be kept:
- Confort et embellissement de la ville
- Culture et rayonnement de la ville
- Eco-citoyenneté
- Loisirs, sport, éducation
- Végétal

**Comment by moustachu** [comment]
@valentinchaput I think there is more to this story than what we already know 🤔 
If I take as an example the "Culture & Patrimoine" category (id 76) : 
- If I try to edit the category title, it does not create another category but update the current one 
- There are 3 proposals linked to this category, which prevent the category deletion
component ID : 138 (https://ecrivons.angers.fr/admin/participatory_processes/BP2019/components/138/manage/)  
proposals ID : 625 / 658 / 850 
- These proposals doesn't have a Published Date, meaning that the don't appear on the Front Office (Search, Index, Show) 
- All the proposals can't be edited on the admin panel because they're not official proposals

All these behavior are correct on this version of the platform. I didn't check other categories but it should be the same.
I suspect an import of old proposals or something even more strange on this process.

Could you ask the client what exactly have been done on this process / module ?

**Comment by valentinchaput** [comment]
👻 😨 
Might be proposals that were created but not published? Like if someone start creating a proposal but don't publish them at the end because they endorse a similar one? Still, it would be strange as category setting happens after comparison. 

I have more on the whole story:
- At first, this process was duplicated from last year's one (https://ecrivons.angers.fr/processes/BP2018), but I'm not sure categories were duplicated (if so, names were edited this year, which is possible as 2018 edition also had 6 categories). 
- They decided to rename the categories (again?) last week in order to match the 5 categories of the voting phase. 
- 60 selected proposals were imported from Proposals to Budgets. 
- In both features, the client has switched categories successfully on each Proposal/Project. 

Does it help?
